---
# a comment
- name: Upgrade All Packages
  hosts: all:!localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: apt dist-upgrade
      apt:
        upgrade: dist
      when: ansible_distribution_file_variety == "Debian"
    - name: yum update
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution_file_variety == "RedHat"
    - name: zypper update
      zypper:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution_file_variety == "SUSE"
